name: Check Styling

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
        sniff: [false]
        include:
          - php: 7.4
            sniff: true

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all

      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint PHP
        run: composer lint:php

      - name: Check PHP files with coding standards
        if: matrix.sniff == 'true'
        run: composer lint:wpcs
